apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 3  # Adjust the number of replicas as per your requirement
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: yaswanthb13/weather-app  # Replace this with your Docker image name
        ports:
        - containerPort: 80
